version: "{build}"

branches:
  only:
    - master

build: false

services:
  - postgresql

environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g lab knex
  - "COPY env.dist .env"
  - "createdb publish"
  - npm run knex

test: false